### PR TITLE
Map generation fix

### PR DESCRIPTION
**Pull request by Wirlie**
@Nubbie I've fixed the bug that you have :P

> Is visible everywhere which is a problem (Isn't flagged to be restricted to just scenery editor)

Additionally I've improve the button size, because in my language (Spanish) this string is not fully shown.
scr56

If you merge this PR, these changes will be shown in your current PR in the OpenRCT2 repository.
Sorry for my bad english xP

### CODE REVIEW

**Comment by Nubbie** [comment]
@Wirlie Have checked out the code, you're an angle for doing this :tada: Really kind :D 

Just a bit curious about the spacing, just so it doesn't collide with other buttons etc :p 
Will test it :D 

**Edit:** Made it a bit easier, often don't check what I've written so it's a bit messy xD

**Comment by Wirlie** [comment]
ok, no problem, if you find a problem with the spacing then I can remake my last commit xP (or just you can add a new commit after this)

PS: I'm not sure if I've understood what you've said xD, sorry if not

**Comment by Nubbie** [comment]
@Wirlie Have now tested it :D 
Thanks a bunch! :tada: :tada: :tada: 

All languages fit within the box and everything works fine! Merged :)

**Comment by Wirlie** [comment]
No problem :), thanks to you

**Comment by Wirlie** [comment]
xD the enhancement label :smile::stuck_out_tongue::cat:

**Pull request merged**
